In [2]:
import numpy as np

In [7]:
print('Enter weights to neuron ',1)

Enter weights to neuron  1


In [40]:
t=np.array([[ 0., -1.],
 [ 1.,  0.],
 [ 1.,  0.],
 [ 2.,  1.]])
for i in range(t.shape[0]):
    for j in range(t.shape[1]):
        if t[i][j]<0:
            t[i][j]=0
print(t)
            

[[0. 0.]
 [1. 0.]
 [1. 0.]
 [2. 1.]]


In [51]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([0,1,1,0])

def neuron(input,wt,bias):
    B=np.tile(bias, (input.shape[0],1))
    z=np.matmul(input,wt.T)+B
    y_pred=activation(z)
    return y_pred
    
def activation(t):
    for i in range(t.shape[0]):
        for j in range(t.shape[1]):
            if t[i][j]<0:
                t[i][j]=0
    return t
        
    
    
l=int(input('Number of layers: '))

for j in range(l):
        m=int(input('Enter the number of inputs: '))
        n=int(input('Enter the number of neurons: '))
        wt=np.zeros((n,m))
        print(wt)
        for i in range(n):
            print('Enter weights to neuron ',i,' as comma separarted list: ')
            wt[i,:]=[float(x) for x in input().split(',')]
        print(wt)
        bias=[float(x) for x in input('Enter bias: ').split(',')]
        bias
        print(neuron(x,wt,bias))
        x=neuron(x,wt,bias)
    

        




Number of layers:  2
Enter the number of inputs:  2
Enter the number of neurons:  2


[[0. 0.]
 [0. 0.]]
Enter weights to neuron  0  as comma separarted list: 


 1,1


Enter weights to neuron  1  as comma separarted list: 


 1,1


[[1. 1.]
 [1. 1.]]


Enter bias:  0,-1


[[0. 0.]
 [1. 0.]
 [1. 0.]
 [2. 1.]]


Enter the number of inputs:  2
Enter the number of neurons:  1


[[0. 0.]]
Enter weights to neuron  0  as comma separarted list: 


 1,-2


[[ 1. -2.]]


Enter bias:  0


[[0.]
 [1.]
 [1.]
 [0.]]
